contact_csv_uploader/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'contacts#index'

  resources :contacts do
    collection { post :import }
  end

  resources :csv_files
end

contact_csv_uploader/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

contact_csv_uploader/app/models/contact.rb
require 'csv'

class Contact < ApplicationRecord
  belongs_to :user
  belongs_to :csv_file

  validates :name,
            :birthday,
            :phone,
            :address,
            :franchise,
            :email,
            :card_number,
            presence: true

  def self.import(file, user)
    contact_file = CsvFile.new log: 'Uploading file..',
                               status: 'Processing'
    contacts_saved = 0
    CSV.foreach(file.path, headers: true) do |row|
      line_parsed = row.to_hash.merge!(user_id: user.id,
                                       csv_file_id: contact_file.id)
      contact = Contact.new line_parsed
      if contact.valid?
        contact.save
        contacts_saved += 1 if contacts_saved.zero?
      else
        errors = contact.errors.full_messages.join(', ')
        contact_file_log = contact_file.log
        contact_file.update(
          log: contact_file_log.concat(row.to_s.concat("\n#{errors}")),
          status: 'Failed'
        )
      end
    end

    return unless contacts_saved.positive?

    contact_file.update(status: 'Finished')
  end
end

contact_csv_uploader/app/models/csv_file.rb
class CsvFile < ApplicationRecord
  has_many :contacts
end

contact_csv_uploader/app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :contacts
end

contact_csv_uploader/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

contact_csv_uploader/app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
    @contacts = Contact.where(user: current_user).page params[:page]
  end

  def new
    @contact = Contact.new
  end

  def import
    Contact.import(params[:file], current_user)

    redirect_to root_url
  end

  private

  def contact_params
    params.require(:contact).permit(:file)
  end
end

contact_csv_uploader/app/controllers/csv_files_controller.rb
class CsvFilesController < ApplicationController
  def index
    @csv_files = Kaminari.paginate_array(Contact.includes(:csv_file)
                                                .where(user_id: 1)
                                                .map(&:csv_file)
                                                .uniq)
                         .page params[:page]
  end

  def show
    @csv_file = CsvFile.find(params[:id])
  end
end

contact_csv_uploader/app/helpers/application_helper.rb
module ApplicationHelper
end

contact_csv_uploader/app/helpers/contacts_helper.rb
module ContactsHelper
end

contact_csv_uploader/app/helpers/csv_files_helper.rb
module CsvFilesHelper
end

contact_csv_uploader/app/views/contacts/index.html.erb
<h1>Contacts</h1>

<%= paginate @contacts %>

<ul>
  <% @contacts.each do |contact| %>
    <li>
      <%= contact.name %>
      <%= contact.birthday %>
      <%= contact.phone %>
      <%= contact.address %>
      <%= contact.franchise %>
      <%= contact.email %>
      <%= contact.card_number %>
      <%= link_to "Uploaded File", contact.csv_file %>
    </li>
  <% end %>
</ul>

<%= link_to "Upload CSV", new_contact_path %>

contact_csv_uploader/app/views/contacts/new.html.erb
<br/>
<b>Upload CSV to import Contacts</b>

<%= form_tag import_contacts_path, multipart: true do %>
  <%= file_field_tag :file%>
  <%= submit_tag "Upload CSV" %>
<% end %>

contact_csv_uploader/app/views/csv_files/index.html.erb
<h1>Imported Contacts Files</h1>

<%= paginate @csv_files %>

<ul>
  <% @csv_files.each do |csv_file| %>
    <li>
      Id: <%= csv_file.id %>
      Log: <%= csv_file.log %>
      Status: <%= csv_file.status %>
    </li>
  <% end %>
</u

contact_csv_uploader/app/views/csv_files/show.html.erb
<ul>
  <li> Log: <%= @csv_file.log %> </li>
  <li> Status: <%= @csv_file.status %> </li>
  <li><%= link_to "voltar", contacts_path %></li>
</ul>

contact_csv_uploader/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ContactCsvUploader</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="navbar-text float-right">
    <% if user_signed_in? %>
      Logged in as <strong><%= current_user.email %></strong>.
      <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
    <% else %>
      <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
      <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
    <% end %>
  </p>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= yield %>
  </body>
</html>